music/urls.py
from django.conf.urls import include,url
from . import views
app_name='music'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^allsongs$', views.allSongs, name='allSongs'),
    # url(r'^addAlbum', views.addAlbum, name='addAlbum'),
    url(r'^get_all_songs', views.get_all_songs, name='get_all_songs'),
    url(r'^get_all_album', views.get_all_album, name='get_all_album'),
    url(r'^addSong', views.addSong, name='addSong'),
    url(r'^addAlbum/$', views.addAlbum, name='addAlbum'),
    url(r'^(?P<album_id>[0-9]+)/addSong/$', views.addSong, name='addSong'),
    url(r'^get_ids', views.get_ids, name='get_ids'),
    url(r'^download_records', views.download_records, name='download_records'),
]

myApp/urls.py
from django.conf.urls import include,url
from django.conf import settings
from music import views
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

urlpatterns = [

   url(r'^admin/', admin.site.urls),
   url(r'^$', views.mainPage, name='mainPage' ),
   url(r'^music/', include('music.urls')),
   url(r'^video/', include('video.urls')),
]

if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk':self.pk})

    def __str__(self):
     return self.album_title+"--" + self.artist+"-- "+ self.genre

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE, related_name="album" )
    #on_delete=models.CASCADE is used to delete all songs in a album if album is deleted.
    #ForeignKey is used to link song with album having some primary key let's say 1.
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=100)
    song_file = models.FileField()

    def __str__(self):
        return self.song_title

@receiver(pre_delete, sender=Album)
def mymodel_delete(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    instance.album_logo.delete(False)

@receiver(pre_delete, sender=Song)
def mymodel_delete(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    instance.song_file.delete(False)

music/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Album, Song


class AlbumForm(forms.ModelForm):

    class Meta:
        model = Album
        fields = ('artist', 'album_title', 'genre', 'album_logo',)


class SongForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ('file_type','song_title', 'song_file',)

music/views.py
from django.http import Http404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from openpyxl.writer.excel import save_virtual_workbook
from django.template import loader
from django.shortcuts import render, get_object_or_404
from .models import Album,Song
from django.views.decorators.csrf import csrf_exempt
import json
from .forms import AlbumForm, SongForm
from openpyxl import Workbook
from boto.s3.key import Key
from django.contrib.sites.shortcuts import get_current_site
from django.core.files.storage import FileSystemStorage
from django.conf import settings
import boto
import sys
def index(request):
   # /music/
   if request.method == "POST":
       form = AlbumForm(request.POST or None, request.FILES or None)
       if form.is_valid():
           album = form.save(commit=False)
           album.album_logo = request.FILES['album_logo']
           print album
           album.save()


   all_albums = Album.objects.all()
   context ={'all_albums':all_albums}
   return render(request, 'music/index.html', context)
   # template= loader.get_template('music/index.html')
   #return HttpResponse(template.render(context, request))
   # /music/712/


def detail(request,album_id):
    form = SongForm(request.POST or None, request.FILES or None)
    album = get_object_or_404(Album, pk=album_id)
    print album
    if form.is_valid():
        song = form.save(commit=False)
        song.album = album
        song.song_file = request.FILES['song_file']
        print song
        song.save()
        link = '/music/' + album_id
        return HttpResponseRedirect(link)
    #return HttpResponse("<h2>Details of album id: "+str(album_id)+"</h2>")
    #try:
     #   album=Album.objects.get(id=album_id)
    #except Album.DoesNotExist:
     #   raise Http404('Album Does Not Exist')
    album= get_object_or_404(Album, pk=album_id)
    songs_list = Song.objects.filter(album=album)
    # print songs_list
    return render(request, "music/detail.html",{'album':album,'songs':songs_list})

def mainPage(request):
    return render(request, "music/mainPage.html",)

def download_records(request):
    AWS_ACCESS_KEY_ID = 'AKIAJWWYE2JIC4CO2AIA'
    AWS_SECRET_ACCESS_KEY = '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'
    END_POINT = 'ap-south-1'
    S3_HOST = 's3.ap-south-1.amazonaws.com'
    BUCKET_NAME = 'chatmis'
    s3_mis_name = settings.S3_SUB_BUCKET2 + "message_records.csv"

    file_name = 'album.csv'
    wb = Workbook()
    ws1 = wb.active
    ws1.title = "Album"
    ws1.append(['Serial no.','album', 'file_type', 'song_title', 'song_file'])
    records = Song.objects.all()
    print records
    i = 0
    for new_record in records:
        i = i + 1
        full_url = ''.join(['http://', get_current_site(request).domain, '/', new_record.song_file.url])
        ws1.append([i,new_record.album.album_title, new_record.file_type, new_record.song_title,full_url ])
    wb.save(file_name)
    return HttpResponseRedirect('https://www.google.com')
    # try:
    #     s3 = boto.s3.connect_to_region(END_POINT, aws_access_key_id=AWS_ACCESS_KEY_ID, aws_secret_access_key=AWS_SECRET_ACCESS_KEY, host=S3_HOST)
    #     bucket = s3.get_bucket(BUCKET_NAME)
    #     k = Key(bucket)
    #     k.key = s3_mis_name
    #     k.set_contents_from_filename(file_name)
    #     print "mis uploaded to s3"
    #     #bucket = s3.get_bucket(BUCKET_NAME)
    #     #k = Key(bucket)
    #     #k.key = 'out.csv'
    #     #k. get_contents_to_filename('hello.csv')
    #     result = dict()
    #     result['status'] = 'success'
    #     return HttpResponseRedirect('https://s3.ap-south-1.amazonaws.com/chatmis/message/message_records.csv')
    # except Exception, exc:
    #     sys.exit( "mail failed; %s" % str(exc) )
    #     result = {"result": "failure", "error_reason": str(exc)}
    #     print "error uploading to s3"
    # return HttpResponseRedirect('/')

def addAlbum(request):
  form = AlbumForm(request.POST or None, request.FILES or None)
  if form.is_valid():
        album = form.save(commit=False)
        album.album_logo = request.FILES['album_logo']
        print album
        album.save()
        # csv_file = request.FILES['album_logo']
        # decoded_file = csv_file.read().decode('utf-8')
        # io_string = io.StringIO(decoded_file)
        # for line in csv.reader(io_string, delimiter=';', quotechar='|'):
        #     for tab in line:
        #         array = tab.split(",")
        #         for value in array:
        #             print value
        return HttpResponseRedirect('/music/')
  return render(request, 'music/addAlbum.html')    

def addSong(request,album_id):
  form = SongForm(request.POST or None, request.FILES or None)
  album = get_object_or_404(Album, pk=album_id)
  print album
  if form.is_valid():
        song = form.save(commit=False)
        song.album = album
        song.song_file = request.FILES['song_file']
        print song
        song.save()
        link = '/music/'+album_id
        return HttpResponseRedirect(link)
  all_albums = Album.objects.all()
  context ={'all_albums':all_albums}      
  return render(request, 'music/addSong.html', context)    

def allSongs(request):
    songs_list = []
    newlist2=[]
    album = Album.objects.all()
    # print album
    for song in album:
          new_song=Song.objects.filter(album=song)
          for song2 in new_song:
               full_url = ''.join(['http://', get_current_site(request).domain, '/', song2.song_file.url])
               songs_list.append({'song_title':song2.song_title,'file_type':song2.file_type,'id':song2.pk,'url':full_url})
          newlist2.append({'album_title':song.album_title,'album_logo_url':song.album_logo.url,'album_songs':songs_list})
          songs_list = []
    # print newlist2
    context = {'album':newlist2}
    return render(request, 'music/allSongs.html', context)

# @csrf_exempt
# def addAlbum(request):
#   if request.method == "POST":
#         file = request.FILES.get('img')
#         print file
#         # album = json.loads(request.body or None, request.FILES or None)
#         result = dict()
#         # print album
#         # if Album.objects.filter(album_title = album['album_title']).count() <= 0:
#         #     savealbum = Album(artist = album['artist'], album_title= album['album_title'], genre= album['genre'],album_logo=album['logo'])
#         #     savealbum.save()
#         result['status'] = 'success'
#         return HttpResponse(json.dumps(result), content_type="application/json")
        
@csrf_exempt
def get_all_songs(request):
    newlist = []
    result = dict()
    new_song = Song.objects.get(pk=request.GET.get('id'))
    full_url = ''.join(['http://', get_current_site(request).domain, '/', new_song.song_file.url])
    newlist.append({'song': full_url,'name':new_song.song_title,'length':new_song.song_file.size, 'pk': new_song.pk})
    # print newlist
    result['list'] = newlist
    return HttpResponse(json.dumps(result), content_type="application/json")

@csrf_exempt
def get_all_album(request):
    newlist = []
    newlist2 = []
    result = dict()
    new_song = Album.objects.all()
    for new in new_song:
      newlist.append({'album': new.album_title, 'pk': new.pk})
    newlist2.append({'list_of_albums':newlist})
    # print newlist2
    result['list'] = newlist2
    return HttpResponse(json.dumps(result), content_type="application/json")

# @csrf_exempt
# def addSong(request):
#         album2 = json.loads(request.body or None, request.FILES or None)
#         result = dict()
#         print album2
#         new_album=Album.objects.get(album_title = album2['album'])
#         savesong = Song(album = new_album, file_type= album2['file_type'], song_title= album2['song_title'])
#         savesong.save()
#         result['status'] = 'success'
#         return HttpResponse(json.dumps(result), content_type="application/json")

@csrf_exempt
def get_ids(request):
    newlist = []
    result = dict()
    new_song2 = Song.objects.all()
    for new in new_song2:
      newlist.append(new.pk)
    print newlist
    result['list'] = newlist
    return HttpResponse(json.dumps(result), content_type="application/json")

music/templates/music/addAlbum.html
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'music/bootstrap.min.css' %}">
<body>
<div class="container" id="myModal" style="background-color: #D3D0CF;  height: 300px;width: 40%;left: 30%;top:150px;position: fixed;">
    <h2>Add Album Here</h2>
  <form class="form-horizontal"  method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    <div class="form-group">
      <label class="control-label col-sm-2" for="artist" >Artist:</label>
      <div class="col-sm-10">
        <input type="text" name="artist" ng-model="album.artist" class="form-control" >
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-2" for="album_title"  >Album Title:</label>
      <div class="col-sm-10">
        <input type="text" name="album_title" ng-model="album.album_title" class="form-control" >
      </div>
    </div>
      <div class="form-group">
      <label class="control-label col-sm-2" for="genre">Genre:</label>
      <div class="col-sm-10">
        <input type="text" name="genre" ng-model="album.genre" class="form-control">
      </div>
      </div>
      <div class="form-group">
      <label class="control-label col-sm-2" for="album_logo" >Album Logo:</label>
      <div class="col-sm-10">
        <input type="file" name="album_logo" data-bind-File ng-model="album.logo" id="imagefile" class="form-control" />
      </div>
      </div>
      <div class="form-group">
      <div class="col-sm-offset-2 col-sm-5">
        <button type="submit" class="form-control btn btn-danger">Submit</button>
      </div>
      </div>
  </form>
    
</div>
</body>

music/templates/music/addSong.html
{% load staticfiles %}
<head>
<title>Add Song</title>
<link rel="stylesheet" href="{% static 'music/bootstrap.min.css' %}">
<script type="text/javascript" src="{% static 'music/detailJavascript.js' %}"></script>
</head>
<body>
<!-- <select name="album" ng-model="song.album" class="form-control" >
          {% for album in all_albums %}
              <option value="{{ album.album_title }}">{{ album.album_title }}</option>
          {%endfor%}    
          </select> -->
<div class="container" id="myModal" style="background-color: #D3D0CF;height: 300px;width: 40%;left: 30%;top:150px;position: fixed;">
    <h2>Add Song Here</h2>
   <form class="form-horizontal"  method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    <div class="form-group">
      <label class="control-label col-sm-2" for="file_type" >File Type:</label>
      <div class="col-sm-10">
         <input type="text" name="file_type" ng-model="song.song_title" class="form-control">
      </div>
    </div>
      <div class="form-group">
      <label class="control-label col-sm-2" for="song_title" >Song Title:</label>
      <div class="col-sm-10">
        <input type="text" name="song_title" ng-model="song.song_title" class="form-control">
      </div>
      </div>
      <div class="form-group">
      <label class="control-label col-sm-2" for="song_file" >Song File:</label>
      <div class="col-sm-10">
        <input type="file" name="song_file" data-bind-File ng-model="song.file" class="form-control" />

      </div>
      </div>
      <div class="col-sm-offset-2 col-sm-5">
        <button type="submit" class="form-control btn btn-danger">Submit</button>
      </div>
  </form>
       
</div>
</body>

music/templates/music/allSongs.html
{% extends 'music/topbar.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <link href="https://fonts.googleapis.com/css?family=Rubik" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'music/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
{% block body %}
<div class="whole" ng-app="myApp" style="position: relative;top: 78px;">
<div class="whole"  ng-controller="faqCtrl">
<div id="indexPage" style="opacity: 1;">
<div style="height: 86%;overflow-y: scroll;">
    <div class="container" style="width: 100%;position: fixed;z-index: 7;top: 60px;">
      <div class="row" style="display: inline-flex;">
          <div class=""><button class="btn btn-primary" style="background-color: black;" ng-click="playsongs()">Play All Songs</button></div>
          <div class=""><button class="btn btn-primary" style="background-color: black;" ng-click="playall()">Play All Songs With Suffle</button></div>
      </div>
    </div>
    <br>
      <h2 style="font-family: cursive;">All Songs List</h2>
      <div class="row" style="width: 100%;">
          {% for album in album %}

              <div class="col-sm-12" style="z-index:5;background-color: white;">
              {% with forloop.counter as myVar %}
                  <br>
                  <div style="padding: 18px;font-size: 15px;letter-spacing: 6px;"><span style="font-family:cursive;left: 10%;background-color: #111;color: #fff;">{{ album.album_title }}</span></div>
{#                  <br><div style="text-align: center;"><img style="height: 100px;width: 200px;left: 10%;" src="../{{album.album_logo.url}}"></div>#}
              {% for song in album.album_songs %}
                 <div style="padding: 6px;font-size: 15px;letter-spacing: 3px;" id="{{ song.id }}">
                     <span style="font-family: 'Rubik', cursive;left: 10%;color: #111;">{{ forloop.counter }}. {{ song.song_title }}-{{ song.file_type }}</span>
                     <span onclick="audioPlay({{ song.id }})"><i style="cursor: pointer;" class= "glyphicon glyphicon-play-circle" onclick='giveUrl("{{ song.url }}")' ></i></span>
                 </div>

              {% endfor %}
              {% endwith %}
              </div>
              <br><br>
              <!-- <div style="max-width: 100%; position: relative;opacity: 1;background-attachment: fixed;background-position: center;background-repeat: no-repeat;background-size: cover;background-image: url('../{{album.album_logo_url}}');min-height: 100%;"></div>
 -->
          {% endfor %}
      </div>
</div>
<div class="songContainer" style="position: fixed;z-index:5;bottom: 0px;width: 100%;background-color: coral;">
    <div id="songDetail">
        <p style="font-size: 15px;">Please click on a song to play</p>
    </div>
     <div style="text-align: center;">
    <audio style="height: 50px;width: 90%;border-radius: 2%;" id="audio" controls><source id="url" src="../../media/Hey_Mama.mp3" type="audio/mpeg"> </audio>
     </div>
</div>
</div>
</div>
</div>
{% endblock %}
</html>

music/templates/music/detail.html
{% extends 'music/topbar.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Rubik" rel="stylesheet">
<link rel="stylesheet" href="{% static 'music/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}/">
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
<script type="text/javascript" src="{% static 'music/detailJavascript.js' %}"></script>
</head>
{% block body %}
<div id="indexPage" style="position: relative;top: 78px;">
{#    <div class="" style=""><a style="text-decoration: none;" href="{% url 'music:addSong' album.id %}"><button class="btn btn-danger">Add Song</button></a></div>#}
     <div class="" style=""><a style="text-decoration: none;"><button class="btn btn-primary" onclick="songButton('{{ album.id }}')" id="songButton">Add Song</button></a></div>
    <div class="row" style="height: 550px; width: 100%;background-color: white;">
<div class="col-sm-4" style="text-align: center;height: 100%;width: 40%;font-family: Serif;"><br>
<img style="height: 240px;width: 320px;border-radius: 5px;z-index: 3;border: outset;" src="../../{{ album.album_logo.url }}">
<h3>Album Title: {{ album.album_title }}</h3>
<h3>Artist: {{ album.artist }}</h3>
<h3>Genre: {{ album.genre }}</h3>
</div>
<div class="col-sm-8" style="height: 100%;width: 60%;overflow-y: scroll;font-family: cursive;"><h1>Songs List</h1><br>
{% for song in songs %}
    <p style="font-size: 15px;" id="{{ song.id }}" style="font-family: 'Rubik', cursive;" >{{ forloop.counter }}. {{ song.song_title }}-{{ song.file_type }}
        <span onclick="audioPlay({{ song.id }})"><i class= "glyphicon glyphicon-play-circle" style="cursor: pointer;" onclick='giveUrl2("{{ song.song_file.url }}")' ></i></span>
       <!-- <img id="getSource" src="{{ song.song_file.url }}" style="height: 0px;width: 0px;"> -->
    </p>
{% endfor %}
</div>
</div>
<div class="songContainer" style="position: fixed;bottom: 0px;width: 100%;background-color: coral;">
    <div id="songDetail">
        <p style="font-size: 15px;">Please click on a song to play</p>
    </div>
    <div style="text-align: center;">
    <audio style="height: 50px;width: 90%;border-radius: 2%;" id="audio" controls><source id="url" src="../../media/Hey_Mama.mp3" type="audio/mpeg"> </audio>
    </div>
</div>
</div>

<div class="container" id="myModal" style="display: none;z-index: 5; background-color: #D3D0CF;height: 300px;width: 40%;left: 30%;top:150px;position: fixed;">
    <span class="close" id="close">&times</span>
    <h2>Add Song Here</h2>
   <form class="form-horizontal" action=""  method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    <div class="form-group">
      <label class="control-label col-sm-2" for="file_type" >File Type:</label>
      <div class="col-sm-10">
         <input type="text" name="file_type" ng-model="song.song_title" class="form-control">
      </div>
    </div>
      <div class="form-group">
      <label class="control-label col-sm-2" for="song_title" >Song Title:</label>
      <div class="col-sm-10">
        <input type="text" name="song_title" ng-model="song.song_title" class="form-control">
      </div>
      </div>
      <div class="form-group">
      <label class="control-label col-sm-2" for="song_file" >Song File:</label>
      <div class="col-sm-10">
        <input type="file" name="song_file" data-bind-File ng-model="song.file" class="form-control" />

      </div>
      </div>
      <div class="col-sm-offset-2 col-sm-5">
        <button type="submit" class="form-control btn btn-danger">Submit</button>
      </div>
  </form>

</div>
 <script type="text/javascript">

         function songButton(id) {
             console.log("Pressed album button");
             var modal = document.getElementById('myModal');
             var opacity = document.getElementById('indexPage');
             modal.style.display = "block";
             opacity.style.opacity = "0.5";
             var span = document.getElementById("close");
             console.log(span);

             span.onclick = function () {
                 modal.style.display = "none";
                 opacity.style.opacity = "1";
             };

         };
</script>

{% endblock %}


</html>

music/templates/music/index.html
{% extends 'music/topbar.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<head>
<link rel="stylesheet" href="{% static 'music/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}/">
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
</head>


{% block body %}
<script type="text/javascript">

         $(document).on("click", "#albumButton", function () {
             console.log("Pressed album button");
             var modal = document.getElementById('myModal');
             var opacity = document.getElementById('indexPage');
             modal.style.display = "block";
             opacity.style.opacity = "0.5";
             var span = document.getElementById("close");
             console.log(span);

             span.onclick = function () {
                 modal.style.display = "none";
                 opacity.style.opacity = "1";
             };

         });
</script>
{# Vijendra Modal section#}
{% verbatim %}
<div id="whole" style="position: relative;top: 78px;" >
{% endverbatim %}
<div id="indexPage"style="opacity: 1;">
<div class="row">
    <div class="col-sm-4"><h3 style="color: black;">Here are all my albums:</h3></div>
    <div class="col-sm-4"></div>
    <div class="col-sm-4"><a><button class="btn btn-info" id="albumButton">Add Album</button></a></div>
</div>

{% if all_albums %}
           <div class="row">
        {% for album in all_albums %}
              <div class="col-sm-3">
                  <img style="height: 200px;width: 80%;border-radius: 5px;z-index: 3;border: outset;" src="../../{{ album.album_logo.url }}"/><br>
                  <a style="text-decoration: none;color:white" href="{% url 'music:detail' album.id %}"><button class="btn btn-success">{{ album.album_title }}</button></a>
              </div>
        {% endfor %}

            </div>
{% else %}
    <h3>No Albums in Database</h3>
{% endif %}
</div>
</div>

<div class="container" id="myModal" style="display: none; background-color: #D3D0CF;  height: 300px;width: 40%;left: 30%;top:150px;position: fixed;">
    <span class="close" id="close">&times</span>
    <h2>Add Album Here</h2>
  <form class="form-horizontal" action=""  method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    <div class="form-group">
      <label class="control-label col-sm-2" for="artist" >Artist:</label>
      <div class="col-sm-10">
        <input type="text" name="artist"  class="form-control" >
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-2" for="album_title"  >Album Title:</label>
      <div class="col-sm-10">
        <input type="text" name="album_title"  class="form-control" >
      </div>
    </div>
      <div class="form-group">
      <label class="control-label col-sm-2" for="genre">Genre:</label>
      <div class="col-sm-10">
        <input type="text" name="genre"  class="form-control">
      </div>
      </div>
      <div class="form-group">
      <label class="control-label col-sm-2" for="album_logo" >Album Logo:</label>
      <div class="col-sm-10">
        <input type="file" name="album_logo"  id="imagefile" class="form-control" />
      </div>
      </div>
      <div class="form-group">
      <div class="col-sm-offset-2 col-sm-5">
        <button type="submit" class="form-control btn btn-danger">Submit</button>
      </div>
      </div>
  </form>

</div>

{% endblock %}

</html>

music/templates/music/mainPage.html
{% extends 'music/topbar.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Music App</title>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
</head>
{% block body %}
<div style="position: relative;top: 78px;" class="mainPageBody">
        <br><br>
        <div class="row">
            <div class="col-sm-4"></div>
            <div style="text-align: center;" class="col-sm-4">
                <a href="/music/"><button class="btn btn-success">Music</button></a>
                <a href="/video/" ><button class="btn btn-success">Video</button></a>
            </div>
        </div>
</div>
{% endblock %}
</html>

music/templates/music/topbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Music{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
   <link rel="stylesheet" href="{% static 'music/bootstrap.min.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
<script type="text/javascript" src="{% static 'music/detailJavascript.js' %}"></script>
</head>
<body>
<div style="position: fixed; width: 100%; top: 0px;z-index: 15;">
<nav class="navbar navbar-inverse" >
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">My App</a>
        </div>

        <!-- Items -->s
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li><a href="/video"><span class="glyphicon glyphicon-hd-video" aria-hidden="true"></span>Videos</a></li>
                <li><a href="/music"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>Albums</a></li>
                <li><a href="/music/allsongs"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>All Songs</a></li>
                <li><a href="/video/addVideo"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Add Video</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="">
{#                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>#}
                    </a>
                </li>
                <li>
                    <a href="">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span> Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
</div>
{% block body %}
{% endblock %}
</body>
</html>