music/urls.py
from django.conf.urls import include,url
from . import views
app_name='music'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^allsongs$', views.allSongs, name='allSongs'),
    # url(r'^addAlbum', views.addAlbum, name='addAlbum'),
    url(r'^get_all_songs', views.get_all_songs, name='get_all_songs'),
    url(r'^get_all_album', views.get_all_album, name='get_all_album'),
    url(r'^addSong', views.addSong, name='addSong'),
    url(r'^addAlbum/$', views.addAlbum, name='addAlbum'),
    url(r'^(?P<album_id>[0-9]+)/addSong/$', views.addSong, name='addSong'),
    url(r'^get_ids', views.get_ids, name='get_ids'),
    url(r'^download_records', views.download_records, name='download_records'),
]

myApp/urls.py
from django.conf.urls import include,url
from django.conf import settings
from music import views
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

urlpatterns = [

   url(r'^admin/', admin.site.urls),
   url(r'^$', views.mainPage, name='mainPage' ),
   url(r'^music/', include('music.urls')),
   url(r'^video/', include('video.urls')),
]

if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

video/urls.py
from django.conf.urls import include,url
from video import views
app_name='video'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^addVideo', views.addVideo, name='addVideo'),
    url(r'^(?P<video_id>[0-9]+)/$', views.detail, name='detail'),
]

video/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django.db import models

# Create your models here.
class Video(models.Model):
    video_title = models.CharField(max_length=100)
    video_file = models.FileField()

    def __str__(self):
        return self.video_title


@receiver(pre_delete, sender=Video)
def mymodel_delete(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    instance.song_file.delete(False)

video/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Video


class VideoForm(forms.ModelForm):

    class Meta:
        model = Video
        fields = ('video_title','video_file',)

video/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import Http404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.shortcuts import render
from .forms import VideoForm
from .models import Video
from django.contrib.sites.shortcuts import get_current_site

# Create your views here.
def index(request):
    newlist =[]
    videos = Video.objects.all()
    for video in videos:
        full_url = ''.join(['http://', get_current_site(request).domain, '/', video.video_file.url])
        newlist.append({'video':video.video_title,'url':full_url,'key':video.pk})
    context = {'videos':newlist}
    return render(request, 'video/index.html', context)

def detail(request,video_id):
  newlist = []
  video= get_object_or_404(Video, pk=video_id)
  full_url = ''.join(['http://', get_current_site(request).domain, '/', video.video_file.url])
  print  video
  print full_url
  newlist.append({'video': video.video_title, 'url': full_url, 'key': video.pk})
  print newlist
  context = {'videos': newlist}
  return render(request, "video/detail.html",context)


def addVideo(request):
  form = VideoForm(request.POST or None, request.FILES or None)
  if form.is_valid():
        video = form.save(commit=False)
        video.video_file = request.FILES['video_file']
        print video
        video.save()
        link = '/video/'
        return HttpResponseRedirect(link)
  context ={}
  return render(request, 'video/addVideo.html', context)

video/templates/video/addVideo.html
{% load staticfiles %}
<head>
<title>Add Video</title>
<link rel="stylesheet" href="{% static 'video/bootstrap.min.css' %}">
</head>
<body>
<div class="container" id="myModal" style="background-color: #D3D0CF;height: 300px;width: 40%;left: 30%;top:150px;position: fixed;">
    <h2>Add Video Here</h2>
   <form class="form-horizontal"  method="post" enctype="multipart/form-data" >
    {% csrf_token %}
      <div class="form-group">
      <label class="control-label col-sm-2" for="video_title" >Video Title:</label>
      <div class="col-sm-10">
        <input type="text" name="video_title" ng-model="song.song_title" class="form-control">
      </div>
      </div>
      <div class="form-group">
      <label class="control-label col-sm-2" for="video_file" >Video File:</label>
      <div class="col-sm-10">
        <input type="file" name="video_file" class="form-control" />

      </div>
      </div>
      <div class="col-sm-offset-2 col-sm-5">
        <button type="submit" class="form-control btn btn-danger">Submit</button>
      </div>
  </form>

</div>
</body>

video/templates/video/detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
   <link rel="stylesheet" href="{% static 'video/bootstrap.min.css' %}">
</head>
<body>
     <div class="row">
     {% for video in videos %}
      <div class="col-sm-4">
     <h3>{{ video.video }}</h3>
     <video width="1280" height="600" controls>
       <source src="{{ video.url }}" type="video/mp4">
  Your browser does not support the video tag.
</video>
         </div>
{% endfor %}
     </div>
</body>
</html>

video/templates/video/index.html
{% extends 'music/topbar.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Videos</title>
    <link rel="stylesheet" href="{% static 'video/bootstrap.min.css' %}">
</head>
{% block body %}
    <div class="container-fluid" style="position: relative;top: 78px;">
          <h1>All videos</h1>
{#          <embed id="divxplayer" type="video/mp4" width="1024" height="768"#}
{#src ="../../media/The Bourne Identity 2002 (1080p x265 10bit Tigole).mkv" autoPlay=\"true\"></embed>#}
       <div class="row">
       {% for video in videos %}
           <div class="col-sm-4" style="height: 100px;">
{#           <video width="320" height="240" controls>#}
{#           <source src="{{ video.url }}" type="video/mp4">#}
{#          Your browser does not support the video tag.#}
{#           </video>#}
           <br>
           <a style="word-wrap: break-word; text-decoration: none;color: black; " href="{% url 'video:detail' video.key %}">{{ video.video }}</a>
               <br>
           <a style="text-decoration: none;" href="{{ video.url }}">Link</a>
           </div>
       {% endfor %}
        </div>
    </div>
{% endblock %}
</html>